trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: "Set Python version"

# Step to create config.ini from pipeline variables
- script: |
    echo "[reddit]" > config/config.ini
    echo "client_id = $(REDDIT_CLIENT_ID)" >> config/config.ini
    echo "client_secret = $(REDDIT_CLIENT_SECRET)" >> config/config.ini
    echo "user_agent = $(REDDIT_USER_AGENT)" >> config/config.ini
    echo "username = $(REDDIT_USERNAME)" >> config/config.ini
    echo "password = $(REDDIT_PASSWORD)" >> config/config.ini

    echo "" >> config/config.ini
    echo "[postgresql]" >> config/config.ini
    echo "db_user = $(POSTGRESQL_DB_USER)" >> config/config.ini
    echo "db_password = $(POSTGRESQL_DB_PASSWORD)" >> config/config.ini
    echo "db_host = $(POSTGRESQL_DB_HOST)" >> config/config.ini
    echo "db_port = $(POSTGRESQL_DB_PORT)" >> config/config.ini
    echo "db_name = $(POSTGRESQL_DB_NAME)" >> config/config.ini
  displayName: "Create config.ini from pipeline variables"
  workingDirectory: "reddit-sentiment-analysis"

- script: pip install --upgrade pip
  displayName: "Upgrade pip"
  workingDirectory: "reddit-sentiment-analysis"

- script: pip install -r requirements.txt
  displayName: "Install dependencies"
  workingDirectory: "reddit-sentiment-analysis"

- script: python etl_pipeline.py
  displayName: "Run pipeline script"
  workingDirectory: "reddit-sentiment-analysis"
