trigger:
  branches:
    include:
      - main
  paths:
    include:
      - reddit-sentiment-analysis/**

schedules:
- cron: "0 13 * * *"  # Runs daily at 1:00 PM UTC
  always: true
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: "Set Python version"

- script: pip install --upgrade pip
  displayName: "Upgrade pip"
  workingDirectory: "reddit-sentiment-analysis"

- script: pip install -r requirements.txt
  displayName: "Install dependencies"
  workingDirectory: "reddit-sentiment-analysis"

- script: python etl_pipeline.py
  displayName: "Run pipeline script"
  workingDirectory: "reddit-sentiment-analysis"
